# Generated by Django 5.1.3 on 2024-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=255),
            preserve_default=False,
        ),
    ]
